### PR TITLE
fix: vitest afterAll fails on Windows

### PR DESCRIPTION
**Pull request by onemen**
this fix this issue here

but is see many warnings from MSW]
```
stderr | app/routes/bookings+/$bookingId.test.tsx > returns 404 for a booking that does not involve the user
[MSW] Warning: captured a request without a matching request handler:

  • GET https://loremflickr.com/512/512/transport

If you still wish to intercept this unhandled request, please create a request handler for it.
Read more: https://mswjs.io/docs/getting-started/mocks

stderr | app/routes/ships_+/$shipId.book.test.tsx > returns booking data from the session
[MSW] Warning: captured a request without a matching request handler:

  • GET https://loremflickr.com/512/512/nature

If you still wish to intercept this unhandled request, please create a request handler for it.
Read more: https://mswjs.io/docs/getting-started/mocks
```

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
We need to change the seeding to not get images from the internet and instead get it from the local file system like we're doing in the epic stack. This means we'll need to download a bunch of images for this.

**Comment by onemen** [comment]
> We need to change the seeding to not get images from the internet and instead get it from the local file system like we're doing in the epic stack. This means we'll need to download a bunch of images for this.

just seed the test.db with few tiny images

**Comment by kentcdodds** [comment]
Yes, we just need to remove anything in the repo that downloads images and instead loads them from the filesystem instead. [like this](https://github.com/epicweb-dev/epic-stack/blob/92a93be9388279b385a4c2fbd83f2d7015b59d71/app/routes/resources%2B/delete-image.test.tsx#L28-L30) [and this](https://github.com/epicweb-dev/epic-stack/blob/92a93be9388279b385a4c2fbd83f2d7015b59d71/prisma/seed.ts#L45-L47)

**Pull request merged**
