### PR TITLE
Add missing brackets to Fly configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
Seems like they were missing.
@kentcdodds

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for this @szepeviktor. I don't understand TOML syntax, so you could be right. However, the Fly docs have it the same way I do: https://fly.io/docs/reference/configuration/#services-concurrency

Have you tested your change in any way?

**Comment by szepeviktor** [comment]
No.

Those docs may be incorrect.
Let us see! https://github.com/superfly/docs/pull/783

**Comment by szepeviktor** [comment]
We are in TOML World :)
Please see https://github.com/superfly/docs/pull/783#issuecomment-1572794983

**Comment by kentcdodds** [comment]
TOML is super confusing. 😆

**Pull request closed without merging**
