### PR TITLE
This is not a PR

### PR DESCRIPTION
**Pull request by szepeviktor**
This is more like an issue with code.

It should be possible to install the application in production.
So everything should be in `"dependencies":` to go from source code to full production installation.

Currently the installation process mixes devdeps with deps.

### CODE REVIEW

**Comment by szepeviktor** [comment]
I know proper production environments are rare as projects are missing [the operations guy](https://github.com/szepeviktor).

**Comment by kentcdodds** [comment]
It's important that development only dependencies are not shipped to the production docker container for a few reasons. Primarily for size. Installing playwright in the docker container and shipping that to prod would be very unnecessary, for example.

This is operating as designed. Thanks anyway!

**Comment by szepeviktor** [comment]
There is a misunderstanding.
I've meant to move production dependencies from devDep to deps in package.json.
https://github.com/npm/feedback/discussions/940 👀

**Comment by kentcdodds** [comment]
Right, and I'm saying we should not do that. We use dev deps to help build our app, then when we go to production we remove those deps and only use the production deps.

**Pull request closed without merging**
