### PR TITLE
chore: use inline type imports and sort imports

### PR DESCRIPTION
**Pull request by ruisaraiva19**

### CODE REVIEW

**Comment by kentcdodds** [comment]
I just noticed this (I wasn't watching the repo, sorry!). Would you like to update the PR to avoid the merge conflicts or would you prefer I just do this myself?

**Comment by ruisaraiva19** [comment]
> I just noticed this (I wasn't watching the repo, sorry!). Would you like to update the PR to avoid the merge conflicts or would you prefer I just do this myself?

No worries, I'll fix the merge conflicts soon.

**Comment by ruisaraiva19** [comment]
@kentcdodds merge conflicts resolved.

**Review by kentcdodds — APPROVED** [review]
Looks great! Thanks a lot!

**Pull request merged**
